### ISSUE TITLE
Error 500 deleting a report

### ISSUE THREAD

**Issue by aascedu** [amyasnikov/validity#137]
### Validity Version

3.0.3

### NetBox Version

4.1.4

### Python Version

3.12.3

### Steps to Reproduce

I tried to delete a report and it raised this error : 
![image](https://github.com/user-attachments/assets/18aaf9f5-9707-456c-91d7-24176a9f01e9)

I think I was able to delete reports before but I updated netbox this morning, so probably it isn't working anymore because of that !

**Comment by amyasnikov** [comment]
Hey @aascedu, please attach the traceback. You can find it in the logs

**Comment by aascedu** [comment]
Sorry I did not activate DEBUG Mode, here it is :
```
netbox-v4.1.1-dev              | Internal Server Error: /plugins/validity/reports/320/delete/
netbox-v4.1.1-dev              | Traceback (most recent call last):
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/relations.py", line 396, in to_representation
netbox-v4.1.1-dev              |     url = self.get_url(value, self.view_name, request, format)
netbox-v4.1.1-dev              |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/netbox/netbox/api/serializers/fields.py", line 37, in get_url
netbox-v4.1.1-dev              |     return self.reverse(view_name, kwargs=kwargs, request=request, format=format)
netbox-v4.1.1-dev              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/reverse.py", line 47, in reverse
netbox-v4.1.1-dev              |     url = _reverse(viewname, args, kwargs, request, format, **extra)
netbox-v4.1.1-dev              |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/reverse.py", line 60, in _reverse
netbox-v4.1.1-dev              |     url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
netbox-v4.1.1-dev              |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
netbox-v4.1.1-dev              |     return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
netbox-v4.1.1-dev              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
netbox-v4.1.1-dev              |     raise NoReverseMatch(msg)
netbox-v4.1.1-dev              | django.urls.exceptions.NoReverseMatch: Reverse for 'vdevice-detail' not found. 'vdevice-detail' is not a valid view function or pattern name.
netbox-v4.1.1-dev              |
netbox-v4.1.1-dev              | During handling of the above exception, another exception occurred:
netbox-v4.1.1-dev              |
netbox-v4.1.1-dev              | Traceback (most recent call last):
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
netbox-v4.1.1-dev              |     response = get_response(request)
netbox-v4.1.1-dev              |                ^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
netbox-v4.1.1-dev              |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
netbox-v4.1.1-dev              |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
netbox-v4.1.1-dev              |     return self.dispatch(request, *args, **kwargs)
netbox-v4.1.1-dev              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/netbox/netbox/views/generic/base.py", line 26, in dispatch
netbox-v4.1.1-dev              |     return super().dispatch(request, *args, **kwargs)
netbox-v4.1.1-dev              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/netbox/utilities/views.py", line 125, in dispatch
netbox-v4.1.1-dev              |     return super().dispatch(request, *args, **kwargs)
netbox-v4.1.1-dev              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/netbox/utilities/views.py", line 39, in dispatch
netbox-v4.1.1-dev              |     return super().dispatch(request, *args, **kwargs)
netbox-v4.1.1-dev              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
netbox-v4.1.1-dev              |     return handler(request, *args, **kwargs)
netbox-v4.1.1-dev              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/netbox/netbox/views/generic/object_views.py", line 443, in post
netbox-v4.1.1-dev              |     obj.delete()
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1183, in delete
netbox-v4.1.1-dev              |     return collector.delete()
netbox-v4.1.1-dev              |            ^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/db/models/deletion.py", line 463, in delete
netbox-v4.1.1-dev              |     signals.pre_delete.send(
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
netbox-v4.1.1-dev              |     response = receiver(signal=self, sender=sender, **named)
netbox-v4.1.1-dev              |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/netbox/core/signals.py", line 164, in handle_deleted_object
netbox-v4.1.1-dev              |     enqueue_event(queue, instance, request.user, request.id, OBJECT_DELETED)
netbox-v4.1.1-dev              |   File "/opt/netbox/netbox/extras/events.py", line 77, in enqueue_event
netbox-v4.1.1-dev              |     'data': serialize_for_event(instance),
netbox-v4.1.1-dev              |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/netbox/extras/events.py", line 35, in serialize_for_event
netbox-v4.1.1-dev              |     return serializer.data
netbox-v4.1.1-dev              |            ^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 571, in data
netbox-v4.1.1-dev              |     ret = super().data
netbox-v4.1.1-dev              |           ^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
netbox-v4.1.1-dev              |     self._data = self.to_representation(self.instance)
netbox-v4.1.1-dev              |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 538, in to_representation
netbox-v4.1.1-dev              |     ret[field.field_name] = field.to_representation(attribute)
netbox-v4.1.1-dev              |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 538, in to_representation
netbox-v4.1.1-dev              |     ret[field.field_name] = field.to_representation(attribute)
netbox-v4.1.1-dev              |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-v4.1.1-dev              |   File "/opt/netbox/venv/lib/python3.12/site-packages/rest_framework/relations.py", line 411, in to_representation
netbox-v4.1.1-dev              |     raise ImproperlyConfigured(msg % self.view_name)
netbox-v4.1.1-dev              | django.core.exceptions.ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
netbox-v4.1.1-dev              | 10.200.84.112 - - [21/Oct/2024:10:03:32 +0000] "POST /plugins/validity/reports/320/delete/?return_url=/plugins/validity/reports/ HTTP/1.1" 500 202937 "http://netbox.ipline.bur:8000/plugins/validity/reports/320/delete/?return_url=/plugins/validity/reports/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
```

**Comment by amyasnikov** [comment]
Before proceeding, please try the latest version (3.0.5) first, I guess the issue may be already fixed there.
